server:
  port: 8080

spring:
  main:
    # Disable startup banner.
    banner-mode: "off"
    # Disable global startup logging from spring
    log-startup-info: false

  application:
    name: proxy


# Proxy configuration
zuul:
  routes:
    config:
      path: /config/**
      url: http://localhost:8090


# See https://spring.io/guides/gs/routing-and-filtering/
# Since we do not use eureka for service discovery we have to define url above.
ribbon:
  eureka:
    enabled: false
