server:
  port: 8090

spring:
  main:
    # Disable startup banner.
    banner-mode: "off"
    # Disable global startup logging from spring
    log-startup-info: false

  application:
    name=config

  datasource:
    url: jdbc:h2:tcp://localhost//${user.dir}/database;SCHEMA=PUBLIC
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate

  # See http://localhost:8090/h2-console
  h2:
    console:
      enabled: true
